FROM golang:1.21 AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY api/ api/
COPY internal/ internal/
COPY pkg/ pkg/
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -a -o thesis-bench ./cmd/thesis-bench

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/thesis-bench .
USER 65532:65532
ENTRYPOINT ["/thesis-bench"]
