---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aigateway.envoyproxy.io
  resources:
  - aigatewayroutes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.imperium.io
  resources:
  - aibreakevenanalyses
  - aibudgetpolicies
  - aifinopsreports
  - aigateways
  - aimodels
  - aiproviders
  - aisovereigntypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.imperium.io
  resources:
  - aibreakevenanalyses/finalizers
  - aibudgetpolicies/finalizers
  - aifinopsreports/finalizers
  - aigateways/finalizers
  - aimodels/finalizers
  - aiproviders/finalizers
  - aisovereigntypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - aiops.imperium.io
  resources:
  - aibreakevenanalyses/status
  - aibudgetpolicies/status
  - aifinopsreports/status
  - aigateways/status
  - aimodels/status
  - aiproviders/status
  - aisovereigntypolicies/status
  verbs:
  - get
  - patch
  - update
