//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBreakEvenAnalysis) DeepCopyInto(out *AIBreakEvenAnalysis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBreakEvenAnalysis.
func (in *AIBreakEvenAnalysis) DeepCopy() *AIBreakEvenAnalysis {
	if in == nil {
		return nil
	}
	out := new(AIBreakEvenAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIBreakEvenAnalysis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBreakEvenAnalysisList) DeepCopyInto(out *AIBreakEvenAnalysisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIBreakEvenAnalysis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBreakEvenAnalysisList.
func (in *AIBreakEvenAnalysisList) DeepCopy() *AIBreakEvenAnalysisList {
	if in == nil {
		return nil
	}
	out := new(AIBreakEvenAnalysisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIBreakEvenAnalysisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBreakEvenAnalysisSpec) DeepCopyInto(out *AIBreakEvenAnalysisSpec) {
	*out = *in
	out.Target = in.Target
	in.AlternativeSelfHosted.DeepCopyInto(&out.AlternativeSelfHosted)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBreakEvenAnalysisSpec.
func (in *AIBreakEvenAnalysisSpec) DeepCopy() *AIBreakEvenAnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(AIBreakEvenAnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBreakEvenAnalysisStatus) DeepCopyInto(out *AIBreakEvenAnalysisStatus) {
	*out = *in
	if in.ManagedMonthlyCostEUR != nil {
		in, out := &in.ManagedMonthlyCostEUR, &out.ManagedMonthlyCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.SelfHostedMonthlyCostEUR != nil {
		in, out := &in.SelfHostedMonthlyCostEUR, &out.SelfHostedMonthlyCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MonthlySavingsEUR != nil {
		in, out := &in.MonthlySavingsEUR, &out.MonthlySavingsEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBreakEvenAnalysisStatus.
func (in *AIBreakEvenAnalysisStatus) DeepCopy() *AIBreakEvenAnalysisStatus {
	if in == nil {
		return nil
	}
	out := new(AIBreakEvenAnalysisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBudgetPolicy) DeepCopyInto(out *AIBudgetPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBudgetPolicy.
func (in *AIBudgetPolicy) DeepCopy() *AIBudgetPolicy {
	if in == nil {
		return nil
	}
	out := new(AIBudgetPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIBudgetPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBudgetPolicyList) DeepCopyInto(out *AIBudgetPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIBudgetPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBudgetPolicyList.
func (in *AIBudgetPolicyList) DeepCopy() *AIBudgetPolicyList {
	if in == nil {
		return nil
	}
	out := new(AIBudgetPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIBudgetPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBudgetPolicySpec) DeepCopyInto(out *AIBudgetPolicySpec) {
	*out = *in
	out.Target = in.Target
	out.BudgetEUR = in.BudgetEUR.DeepCopy()
	in.Actions.DeepCopyInto(&out.Actions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBudgetPolicySpec.
func (in *AIBudgetPolicySpec) DeepCopy() *AIBudgetPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AIBudgetPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBudgetPolicyStatus) DeepCopyInto(out *AIBudgetPolicyStatus) {
	*out = *in
	if in.CurrentSpendEUR != nil {
		in, out := &in.CurrentSpendEUR, &out.CurrentSpendEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ProjectedMonthlySpendEUR != nil {
		in, out := &in.ProjectedMonthlySpendEUR, &out.ProjectedMonthlySpendEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBudgetPolicyStatus.
func (in *AIBudgetPolicyStatus) DeepCopy() *AIBudgetPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AIBudgetPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIFinOpsReport) DeepCopyInto(out *AIFinOpsReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIFinOpsReport.
func (in *AIFinOpsReport) DeepCopy() *AIFinOpsReport {
	if in == nil {
		return nil
	}
	out := new(AIFinOpsReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIFinOpsReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIFinOpsReportList) DeepCopyInto(out *AIFinOpsReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIFinOpsReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIFinOpsReportList.
func (in *AIFinOpsReportList) DeepCopy() *AIFinOpsReportList {
	if in == nil {
		return nil
	}
	out := new(AIFinOpsReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIFinOpsReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIFinOpsReportSpec) DeepCopyInto(out *AIFinOpsReportSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIFinOpsReportSpec.
func (in *AIFinOpsReportSpec) DeepCopy() *AIFinOpsReportSpec {
	if in == nil {
		return nil
	}
	out := new(AIFinOpsReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIFinOpsReportStatus) DeepCopyInto(out *AIFinOpsReportStatus) {
	*out = *in
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
	if in.TotalCostEUR != nil {
		in, out := &in.TotalCostEUR, &out.TotalCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ProjectedMonthlyCostEUR != nil {
		in, out := &in.ProjectedMonthlyCostEUR, &out.ProjectedMonthlyCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.TopModels != nil {
		in, out := &in.TopModels, &out.TopModels
		*out = make([]ModelCost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SovereigntyFindings != nil {
		in, out := &in.SovereigntyFindings, &out.SovereigntyFindings
		*out = make([]SovereigntyFinding, len(*in))
		copy(*out, *in)
	}
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]Recommendation, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIFinOpsReportStatus.
func (in *AIFinOpsReportStatus) DeepCopy() *AIFinOpsReportStatus {
	if in == nil {
		return nil
	}
	out := new(AIFinOpsReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGateway) DeepCopyInto(out *AIGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGateway.
func (in *AIGateway) DeepCopy() *AIGateway {
	if in == nil {
		return nil
	}
	out := new(AIGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGatewayList) DeepCopyInto(out *AIGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGatewayList.
func (in *AIGatewayList) DeepCopy() *AIGatewayList {
	if in == nil {
		return nil
	}
	out := new(AIGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGatewaySpec) DeepCopyInto(out *AIGatewaySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Telemetry = in.Telemetry
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(GatewayAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGatewaySpec.
func (in *AIGatewaySpec) DeepCopy() *AIGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGatewayStatus) DeepCopyInto(out *AIGatewayStatus) {
	*out = *in
	if in.GovernedNamespaces != nil {
		in, out := &in.GovernedNamespaces, &out.GovernedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGatewayStatus.
func (in *AIGatewayStatus) DeepCopy() *AIGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(AIGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIModel) DeepCopyInto(out *AIModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIModel.
func (in *AIModel) DeepCopy() *AIModel {
	if in == nil {
		return nil
	}
	out := new(AIModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIModelList) DeepCopyInto(out *AIModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIModelList.
func (in *AIModelList) DeepCopy() *AIModelList {
	if in == nil {
		return nil
	}
	out := new(AIModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIModelSpec) DeepCopyInto(out *AIModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIModelSpec.
func (in *AIModelSpec) DeepCopy() *AIModelSpec {
	if in == nil {
		return nil
	}
	out := new(AIModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIModelStatus) DeepCopyInto(out *AIModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIModelStatus.
func (in *AIModelStatus) DeepCopy() *AIModelStatus {
	if in == nil {
		return nil
	}
	out := new(AIModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProvider) DeepCopyInto(out *AIProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProvider.
func (in *AIProvider) DeepCopy() *AIProvider {
	if in == nil {
		return nil
	}
	out := new(AIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderList) DeepCopyInto(out *AIProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderList.
func (in *AIProviderList) DeepCopy() *AIProviderList {
	if in == nil {
		return nil
	}
	out := new(AIProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderSpec) DeepCopyInto(out *AIProviderSpec) {
	*out = *in
	in.Pricing.DeepCopyInto(&out.Pricing)
	in.Compliance.DeepCopyInto(&out.Compliance)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderSpec.
func (in *AIProviderSpec) DeepCopy() *AIProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AIProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderStatus) DeepCopyInto(out *AIProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderStatus.
func (in *AIProviderStatus) DeepCopy() *AIProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AIProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AISovereigntyPolicy) DeepCopyInto(out *AISovereigntyPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AISovereigntyPolicy.
func (in *AISovereigntyPolicy) DeepCopy() *AISovereigntyPolicy {
	if in == nil {
		return nil
	}
	out := new(AISovereigntyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AISovereigntyPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AISovereigntyPolicyList) DeepCopyInto(out *AISovereigntyPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AISovereigntyPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AISovereigntyPolicyList.
func (in *AISovereigntyPolicyList) DeepCopy() *AISovereigntyPolicyList {
	if in == nil {
		return nil
	}
	out := new(AISovereigntyPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AISovereigntyPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AISovereigntyPolicySpec) DeepCopyInto(out *AISovereigntyPolicySpec) {
	*out = *in
	in.DataResidency.DeepCopyInto(&out.DataResidency)
	out.SensitiveData = in.SensitiveData
	out.Audit = in.Audit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AISovereigntyPolicySpec.
func (in *AISovereigntyPolicySpec) DeepCopy() *AISovereigntyPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AISovereigntyPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AISovereigntyPolicyStatus) DeepCopyInto(out *AISovereigntyPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AISovereigntyPolicyStatus.
func (in *AISovereigntyPolicyStatus) DeepCopy() *AISovereigntyPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AISovereigntyPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRule) DeepCopyInto(out *AuditRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRule.
func (in *AuditRule) DeepCopy() *AuditRule {
	if in == nil {
		return nil
	}
	out := new(AuditRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakEvenTarget) DeepCopyInto(out *BreakEvenTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakEvenTarget.
func (in *BreakEvenTarget) DeepCopy() *BreakEvenTarget {
	if in == nil {
		return nil
	}
	out := new(BreakEvenTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetActions) DeepCopyInto(out *BudgetActions) {
	*out = *in
	if in.OnWarning != nil {
		in, out := &in.OnWarning, &out.OnWarning
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OnCritical != nil {
		in, out := &in.OnCritical, &out.OnCritical
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OnHardLimit != nil {
		in, out := &in.OnHardLimit, &out.OnHardLimit
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetActions.
func (in *BudgetActions) DeepCopy() *BudgetActions {
	if in == nil {
		return nil
	}
	out := new(BudgetActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetTarget) DeepCopyInto(out *BudgetTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetTarget.
func (in *BudgetTarget) DeepCopy() *BudgetTarget {
	if in == nil {
		return nil
	}
	out := new(BudgetTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataResidencyRule) DeepCopyInto(out *DataResidencyRule) {
	*out = *in
	if in.AllowedZones != nil {
		in, out := &in.AllowedZones, &out.AllowedZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenZones != nil {
		in, out := &in.ForbiddenZones, &out.ForbiddenZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataResidencyRule.
func (in *DataResidencyRule) DeepCopy() *DataResidencyRule {
	if in == nil {
		return nil
	}
	out := new(DataResidencyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAuth) DeepCopyInto(out *GatewayAuth) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAuth.
func (in *GatewayAuth) DeepCopy() *GatewayAuth {
	if in == nil {
		return nil
	}
	out := new(GatewayAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCost) DeepCopyInto(out *ModelCost) {
	*out = *in
	out.CostEUR = in.CostEUR.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCost.
func (in *ModelCost) DeepCopy() *ModelCost {
	if in == nil {
		return nil
	}
	out := new(ModelCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCompliance) DeepCopyInto(out *ProviderCompliance) {
	*out = *in
	if in.AllowedCountries != nil {
		in, out := &in.AllowedCountries, &out.AllowedCountries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCompliance.
func (in *ProviderCompliance) DeepCopy() *ProviderCompliance {
	if in == nil {
		return nil
	}
	out := new(ProviderCompliance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPricing) DeepCopyInto(out *ProviderPricing) {
	*out = *in
	out.InputTokenPricePerMillion = in.InputTokenPricePerMillion.DeepCopy()
	out.OutputTokenPricePerMillion = in.OutputTokenPricePerMillion.DeepCopy()
	if in.FixedMonthlyCost != nil {
		in, out := &in.FixedMonthlyCost, &out.FixedMonthlyCost
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPricing.
func (in *ProviderPricing) DeepCopy() *ProviderPricing {
	if in == nil {
		return nil
	}
	out := new(ProviderPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendation) DeepCopyInto(out *Recommendation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendation.
func (in *Recommendation) DeepCopy() *Recommendation {
	if in == nil {
		return nil
	}
	out := new(Recommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportTarget) DeepCopyInto(out *ReportTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportTarget.
func (in *ReportTarget) DeepCopy() *ReportTarget {
	if in == nil {
		return nil
	}
	out := new(ReportTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHostedOption) DeepCopyInto(out *SelfHostedOption) {
	*out = *in
	out.MonthlyGpuCostEUR = in.MonthlyGpuCostEUR.DeepCopy()
	if in.EstimatedOpsCostEUR != nil {
		in, out := &in.EstimatedOpsCostEUR, &out.EstimatedOpsCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageNetworkCostEUR != nil {
		in, out := &in.StorageNetworkCostEUR, &out.StorageNetworkCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MigrationCostEUR != nil {
		in, out := &in.MigrationCostEUR, &out.MigrationCostEUR
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHostedOption.
func (in *SelfHostedOption) DeepCopy() *SelfHostedOption {
	if in == nil {
		return nil
	}
	out := new(SelfHostedOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensitiveDataRule) DeepCopyInto(out *SensitiveDataRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensitiveDataRule.
func (in *SensitiveDataRule) DeepCopy() *SensitiveDataRule {
	if in == nil {
		return nil
	}
	out := new(SensitiveDataRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SovereigntyFinding) DeepCopyInto(out *SovereigntyFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SovereigntyFinding.
func (in *SovereigntyFinding) DeepCopy() *SovereigntyFinding {
	if in == nil {
		return nil
	}
	out := new(SovereigntyFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}
