apiVersion: batch/v1
kind: Job
metadata:
  name: gov-ar-experiment
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gov-ar-experiment
    spec:
      restartPolicy: Never
      containers:
        - name: experiment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - {{ .Values.experiment.command | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
